# Generated by Django on 2026-05-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_magiclinktoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MagicLinkToken',
        ),
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
