name: Django CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: support_db
          POSTGRES_USER: support_user
          POSTGRES_PASSWORD: support_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U support_user -d support_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SECRET_KEY: ci-secret-key
      DEBUG: "False"
      ALLOWED_HOSTS: localhost,127.0.0.1
      DATABASE_URL: postgresql://support_user:support_password@localhost:5432/support_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check Django project
        run: python manage.py check

      - name: Run migrations
        run: python manage.py migrate --no-input

      - name: Run tests
        run: python manage.py test
